# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!
target 'Rx+Network' do
pod 'RxSwift'
pod 'RxCocoa'
pod 'NSObject+Rx'
pod 'Moya/RxSwift'
pod 'ObjectMapper'
pod 'GzipSwift'
end
